csname: Metrics
on:
  schedule:
    - cron: "0 6 * * *" # atualiza 1x por dia
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.metrics2 }}

          # Base
          base: repositories
          config_timezone: America/Sao_Paulo

          # Linguagens
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_threshold: 2%
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_indepth: yes

          # Visual (clean / claro)
          config_display: large
          config_octicon: yes
          config_padding: 8%
          config_border: yes
